[package]
name = "rmapbash"
version = "0.1.0"
authors = ["saltire sable <saltiresable@gmail.com>"]
edition = "2018"

[dependencies]
hematite-nbt = "0.4"
flate2 = "1.0"
regex = "1.1"
serde_json = "1.0"
